Pubsub (#182)
* Added Handling of Ping and pool join request process

* ensure the JoinPoolRequest announcement can be initiated once only

* add the peerID of announcer to a list and no longer accepts the pubsub

Also added lock on the bl.members

* Auto-run FetchUsersAndPopulateSets if not run for the past x hours from pubsub

This is the failsafe to ensure that we at least run this method every x hours even if for any reason pubsubs are not received

* Corrected shutdown error

* enhancewd start of FetchUsersAndPopulateSets

1- If the members list is empty also call pool/requests endpoint to see who voted and it self voted move status to UnKnown
2- used bl_pool methods instead of directly calling blockchain
3- corrected some types
4- added methods to FetchUsersAndPopulateSets for start

* Updating Peerstore with pool nodes

* joinpool final draft

1- added clean peerstore
2- udpate poolName in config file after joinpool
3- check the pool members periodically to see if the join happened

* first issue correction after testing

1- poolname contained extra strings "/explore.fula/pools/"
2- added error priniting to FetchUsersAndPopulateSets

* switched to callBlockchain

since calls were made on the same machine we could not use fxexchange methods to make calls

* corrected some bugs in reading invalid peerid

* Added a parameter --generateNodeKey to generate node key from identity for node

hexadecimal presentation of identity

* corrected lint error

Error: ./blox/options.go:53:20: the argument is already a string, there's no need to use fmt.Sprintf (S1025)

* corrected test files

* Update example_test.go

* reoved t *testing.T

* corrected announcement tests

1- We need to stop adding peers to peer store for each received announcements but for now tests fail if we do not
2- We need to change the blockchain endpoint to 127.0.0.1:4000

* adding to peerstore moved to process

* Added tests for ping

corrected ping errors and added tests for it

* Added test for announcements

* first draft of full testcase

* Update announcements.go

* added example

* Corrected vote method

* added some logs

* commented unused code

* updated tests

* Update example_test.go